request:
  protocol: http # 可缺省，默认http协议
  host: migoo.xyz # 可缺省，默认 127.0.0.1
  port: 80 #可缺省，http协议默认80，https默认443
  method: post # 可缺省，默认 GET
  headers:
    X-Header: migoo
report: # 可缺省，配置测试报告
  listener: # 可缺省，测试报告实现类
  output: # 可缺省，测试报告保存地址
#email: # 邮件相关信息，测试完毕后邮件发送测试报告 可缺省
#  host: # 邮件发送服务器 请使用SMTP服务 如： smtp.163.com
#  port: # 邮件发送服务器端口 如：25
#  user: # 发件人邮箱地址 如：xxx_yyy@163.com
#  password: # 发件人邮箱密码
#  tolist: # 收件人列表
#    - mi_xiao@qq.com # 收件人列表1
