- testclass: JDBCDataSource
  variable_name: JDBCDataSource_var
  url: 'jdbc:mysql://47.106.232.130:3306/migoo?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8&failOverReadOnly=false'
  username: 'migoo'
  password: '123456qq'
  max_active: '10'
  max_wait: '60000'
  driver: com.mysql.cj.jdbc.Driver
- testclass: HttpDefaults
  protocol: http
  host: migoo.xyz